### PR TITLE
Implemented Traefik reverse proxy

### PR DESCRIPTION
**Pull request by jraviotta**
Traefik allows dynamic load balancing and routing.

### CODE REVIEW

**Comment by notVitaliy** [comment]
@jraviotta Can you catch this branch up with master?

**Comment by notVitaliy** [comment]
Looks like you did a weird merge or rebase. All the changes from master are showing in the diff.

Maybe `cherry-pick` your commits into a clean branch off of master?

**Comment by Shawn8901** [comment]
as there is a separate commit for rebase, i think you did not really a rebase. Rebase moves the inital commit to a new parent commit, so this commit is edited. the rebase should not result in a commit, as far as i know. 

Maybe you did merge both? 
Instead a cherry-pick you can also still rebase, and skip those commits you dont want. but be careful with this, as its editing commits you can destroy your commits.

**Comment by jraviotta** [comment]
closing this in favor of a PR without drama.

**Pull request closed without merging**
